// SPRINT BV — KİMLİK alias kaynak tablosu (katalog `alias` alanının TEK kaynağı).
//
// ALIAS = "bu ham ad BU katalog kaydını adlandırır". İKAME DEĞİLDİR.
// Kurallar (her satırın 3. elemanı):
//   urun    — aynı ürünün adı (marka+ürün birebir, ör. "château biscuit" → chateau_biscuit)
//   jenerik — jenerik ad → katalogda o sınıfın jenerik/TEK temsilcisi (ör. "chocolate" → choc)
//   yazim   — yazım/dil varyantı (ör. "hallertauer", "wiener malz", "kölsh")
//   kod     — üretici ürün kodu (yalnız maya; dizgide token olarak aranır, ör. "wlp001")
//
// KAYNAK: V2 (_v2_parser.js MALT_ALIAS/HOP_ALIAS) + V3 (_v3_cikarim.js MALT_EK/HOP_EK) tablolarının
// KİMLİK olan satırları + 376K korpus frekans analizinin (working/_bv_frekans.json) en sık ham adları.
// Her ham ad korpusta görülmek ZORUNDA (kapı: working/_bv_kapi.js); fiziksel özellik kapısı (malt renk °L,
// hop alfa, maya attenuation) katalog değeriyle karşılaştırılır.
//
// BİLİNÇLİ OLARAK ALIAS YAPILMAYANLAR (V2/V3'te eşleme var ama kimlik DEĞİL) → REDDET listesi.
'use strict';

const MALT = [
  // ── baz: Amerikan 2-row / 6-row (katalogda sınıfın TEK üyesi Briess) ──
  ['2-row brewers malt', 'briess_pale', 'urun'],
  ['2-row', 'briess_pale', 'jenerik'],
  ['american 2-row', 'briess_pale', 'jenerik'],
  ['pale malt, 2 row, us', 'briess_pale', 'jenerik'],
  ['6-row brewers malt', 'briess_6row', 'urun'],
  ['6-row', 'briess_6row', 'jenerik'],
  ['pale malt, 6 row, us', 'briess_6row', 'jenerik'],
  // ── baz: İngiliz/Avrupa pale ale (katalog pale_ale = jenerik Pale Ale Malt) ──
  ['pale ale', 'pale_ale', 'jenerik'],
  ['pale malt', 'pale_ale', 'jenerik'],
  ['british pale', 'pale_ale', 'jenerik'],
  ['english pale', 'pale_ale', 'jenerik'],
  ['pale ale malz', 'pale_ale', 'yazim'],
  ['crisp pale ale malt', 'pale_ale', 'jenerik'],
  // ── Maris Otter (arpa ÇEŞİDİ; katalog maris jenerik) ──
  ['maris otter pale', 'maris', 'yazim'],
  ['maris otter malt', 'maris', 'yazim'],
  ['marris otter', 'maris', 'yazim'],
  ['warminster floor-malted maris otter', 'maris', 'jenerik'],
  ['golden promise', 'golden_promise', 'urun'],
  // ── pilsner ──
  ['pilsen malt', 'pilsner', 'yazim'],
    ['pilsner malz', 'pilsner', 'yazim'],
  ['german pilsner', 'pilsner', 'jenerik'],
  ['pilsen', 'pilsner', 'yazim'],
  ['château pilsen 2-row', 'chateau_pils', 'urun'],
    ['château pale ale 2-row', 'chateau_bld', 'urun'],
  ['floor-malted bohemian pilsner', 'bohemian', 'urun'],
  ['best malz pilsner', 'best_pils', 'urun'],
  ['best malz munich', 'best_munich', 'urun'],
    // ── buğday ──
  ['white wheat', 'wheat', 'jenerik'],
  ['wheat malt, white', 'wheat', 'jenerik'],
  ['white wheat malt', 'wheat', 'jenerik'],
    ['pale wheat malt', 'wheat', 'jenerik'],
    ['wheat malt', 'wheat', 'jenerik'],
  ['malted wheat', 'wheat', 'jenerik'],
  ['red wheat', 'wheat', 'jenerik'],
  ['wheat, red', 'wheat', 'jenerik'],
  ['german wheat', 'wheat', 'jenerik'],
  ['weizenmalz hell', 'wheat', 'yazim'],
  ['dark wheat', 'dark_wheat', 'jenerik'],
  ['flaked wheat', 'flaked_wheat', 'jenerik'],
  ['wheat, flaked', 'flaked_wheat', 'yazim'],
    ['raw wheat', 'rwh', 'jenerik'],
  ['midnight wheat malt', 'midnight', 'urun'],
  ['chocolate wheat', 'roast_wheat', 'urun'],
  // ── Munich / Vienna ──
  ['munich light', 'munich_light', 'jenerik'],
  ['munich type i', 'munich_light', 'urun'],
  ['münchner malz typ i', 'munich_light', 'yazim'],
  ['munich type ii', 'dark_munich', 'urun'],
  ['dark munich', 'dark_munich', 'jenerik'],
  ['german munich', 'munich', 'jenerik'],
  ['munich', 'munich', 'jenerik'],
  ['wiener malz', 'vienna', 'yazim'],
    ['german vienna', 'vienna', 'jenerik'],
  // ── crystal/caramel — yalnız katalogda AYNI °L'li kayıt olanlar (en-yakın-L = İKAME, alias DEĞİL) ──
  ['caramel malt 10l', 'c10', 'urun'], ['crystal 10l', 'c10', 'jenerik'],
  ['caramel malt 20l', 'c20', 'urun'], ['crystal 20l', 'c20', 'jenerik'],
  ['caramel malt 40l', 'c40', 'urun'], ['crystal 40l', 'c40', 'jenerik'],
  ['caramel malt 60l', 'c60', 'urun'], ['caramel/crystal 60l', 'c60', 'jenerik'], ['crystal 60l', 'c60', 'jenerik'],
  ['2-row caramel malt 60l', 'c60', 'urun'], ['british crystal 50-60l', 'c60', 'jenerik'],
  ['caramel malt 80l', 'c80', 'urun'], ['crystal 80l', 'c80', 'jenerik'],
  ['british crystal 70-80l', 'c80', 'jenerik'], ['dark crystal 80l', 'c80', 'jenerik'],
  ['caramel malt 120l', 'c120', 'urun'], ['crystal 120l', 'c120', 'jenerik'],
  ['caramel/crystal 150l', 'c150', 'jenerik'],   ['extra dark crystal 160l', 'crystal_extra', 'urun'],
  ['cara 45l', 'cara45', 'urun'],
  // ── Weyermann/Castle/Best cara ürünleri (ürün adı birebir) ──
  ['carapils malt', 'carapils', 'urun'],
  ['cara-pils/dextrine', 'carapils', 'yazim'],
  ['dextrine malt (cara-pils)', 'carapils', 'yazim'],
  ['carafoam', 'cara_foam', 'urun'],
  ['carared', 'cara_red', 'urun'],
  ['carahell', 'cara_hell', 'urun'],
  ['caraaroma', 'cara_aroma', 'urun'],
  ['carabelge', 'cara_belge', 'urun'],
  ['carawheat', 'cara_wheat', 'urun'],
  ['carabohemian', 'cara_dark', 'urun'],
  ['caramunich i', 'cara_munich1', 'urun'],
  ['caramunich ii', 'cara_munich2', 'urun'],
  ['caramunich iii', 'cara_munich3', 'urun'],
  ['cara gold', 'chateau_cara_gold', 'urun'],
  ['red x', 'best_redx', 'urun'],
  ['château biscuit', 'chateau_biscuit', 'urun'],
    // Carafa: katalogdaki crf1/crf2/crf3 "(Debittered)" = Weyermann Carafa SPECIAL (kabuksuz).
  // Kabuklu "carafa i/ii/iii" AYRI ürün → alias DEĞİL (REDDET'te).
  ['carafa special ii', 'crf2', 'urun'],
  ['carafa special iii', 'crf3', 'urun'],
  ['carafa special i', 'crf1', 'urun'],
  ['de-husked caraf iii', 'crf3', 'yazim'],
  ['de-husked caraf ii', 'crf2', 'yazim'],
  // ── özel / koyu ──
  ['victory malt', 'victory', 'urun'],
  ['american victory', 'victory', 'urun'],
  ['special roast', 'briess_sroast', 'urun'],
  ['honey malt', 'hml', 'urun'],
  ['biscuit md', 'bisk', 'jenerik'],
  ['melanoidin', 'mel', 'jenerik'],
  ['aromatic', 'aromatic', 'jenerik'],
  ['aromatic barley malt', 'aromatic', 'jenerik'],
  ['aromatic (munich) malt', 'aromatic', 'jenerik'],
    ['acid malt', 'acid', 'jenerik'],
  ['sauermalz', 'acid', 'yazim', 'Almanca ad (Sauermalz = Acidulated Malt); korpus renk örneği n=2'],
  ['chocolate', 'choc', 'jenerik'],
  ['american chocolate', 'choc', 'jenerik'],
  ['pale chocolate', 'pale_choc', 'jenerik'],
  ['black malt', 'black', 'jenerik'],
  ['blackprinz', 'dehusked_black', 'jenerik'],
  ['crisp brown', 'brown', 'jenerik'],
  ['crisp amber', 'amber', 'jenerik'],
  ['smoked malt', 'smoked', 'jenerik'],
  ['german rauch smoked', 'smoked', 'yazim'],
  ['peated malt', 'smoked_peat', 'jenerik'],
  ['rye malt', 'rye', 'jenerik'],
  ['malted rye', 'rye', 'jenerik'],
  ['oat malt', 'oat_malt', 'jenerik'],
  // ── adjunct ──
  ['flaked oats', 'oat', 'jenerik'],
  ['oat flakes', 'oat', 'yazim'],
  ['rolled oats', 'oat', 'yazim'],
  ['quaker quick oats', 'oat', 'jenerik'],
  ['haferflocken', 'oat', 'yazim'],
  ['flaked barley', 'fbar', 'jenerik'],
  ['barley, flaked', 'fbar', 'yazim'],
  ['flaked corn', 'corn', 'jenerik'],
  ['corn, flaked', 'corn', 'yazim'],
  ['flaked rice', 'rice_flaked', 'jenerik'],
  ['rice, flaked', 'rice_flaked', 'yazim'],
  ['flaked rye', 'flaked_rye', 'jenerik'],
  ['rye, flaked', 'flaked_rye', 'yazim'],
  ['rice hulls', 'rice_hulls', 'jenerik'],
  // ── şeker ──
  ['corn sugar (dextrose)', 'dex', 'jenerik'],
  ['dextrose (corn sugar)', 'dex', 'jenerik'],
  ['corn sugar', 'dex', 'jenerik'],
  ['dextrose', 'dex', 'jenerik'],
  ['cane sugar', 'sek', 'jenerik'],
  ['sugar, table (sucrose)', 'sek', 'jenerik'],
  ['sucrose (table sugar)', 'sek', 'jenerik'],
  ['table sugar', 'sek', 'jenerik'],
  ['white sugar', 'sek', 'jenerik'],
  ['brown sugar', 'light_brown', 'jenerik'],
  ['brown sugar, dark', 'dark_brown', 'jenerik'],
  ['lactose (milk sugar)', 'lak', 'jenerik'],
  ['milk sugar (lactose)', 'lak', 'jenerik'],
  ['lactose', 'lak', 'jenerik'],
  ['honey', 'bal', 'jenerik'],
  ['clover honey', 'bal', 'jenerik', 'bal türü; renk çiçeğe göre değişir, katalog bal jenerik'],
  ['orange blossom honey', 'bal', 'jenerik'],
  ['honey, clover', 'bal', 'jenerik'],
  ['maple syrup', 'maple', 'jenerik', 'korpus renk 35°L (BeerSmith varsayılanı) vs katalog 5 — kimlik tartışmasız, fark katalog/korpus değer meselesi'],
  ['candi syrup d-180', 'candy_drk', 'urun'],
  // ── L0'da yalnız katalog ID'siyle eşleşenler: ID çözümü genel olarak GÜVENSİZ ('rice' id'si = pirinç
  //    KABUĞU, korpusta 'rice' = pirinç adjunct) → kimlik olanlar AÇIK alias yapılır, ID eşlemesi kalkar ──
  ['pilsner', 'pilsner', 'jenerik'], ['vienna', 'vienna', 'jenerik'], ['rye', 'rye', 'jenerik'],
  ['molasses', 'molasses', 'jenerik'], ['turbinado', 'turbinado', 'jenerik', 'ad birebir; ham şeker rengi partiye göre değişir (korpus 10 / katalog 5) — DEĞER farkı'], ['treacle', 'treacle', 'jenerik', 'ad birebir; korpus renk medyanı 0°L fiziksel olarak imkânsız (treacle siyah) → korpus değeri bozuk, katalog 100 makul'],
  ['pearl', 'pearl', 'jenerik'], ['halcyon', 'halcyon', 'jenerik'], ['carapils', 'carapils', 'urun'],
  ['spelt', 'spelt', 'jenerik', 'ad birebir; spelt maltı rengi malthaneye göre 2-5°L — DEĞER farkı'], ['buckwheat', 'buckwheat', 'jenerik'], ['sinamar', 'sinamar', 'urun'],
];

const HOP = [
  ['east kent golding', 'ekg', 'yazim'], ['east kent goldings', 'ekg', 'yazim'], ['goldings, east kent', 'ekg', 'yazim'],
  ['kent goldings', 'ekg', 'yazim'], ['golding', 'ekg', 'jenerik'], ['goldings', 'ekg', 'jenerik'], ['ekg', 'ekg', 'yazim'],
  ['fuggle', 'fuggles', 'yazim'],
  ['hallertau', 'hrtau', 'jenerik'], ['hallertauer', 'hrtau', 'yazim'], ['hallertauer mittelfrüh', 'hrtau', 'yazim'],
  ['hallertau mittelfrüh', 'hrtau', 'yazim'], ['hallertau mittelfruh', 'hrtau', 'yazim'], ['hallertauer mittelfruh', 'hrtau', 'yazim'],
  ['hallertauer mittelfrüher', 'hrtau', 'yazim'], ['hallertauer mittelfrueh', 'hrtau', 'yazim'], ['mittelfrueh', 'hrtau', 'yazim'],
  ['styrian golding', 'styrian', 'yazim'],   ['czech saaz', 'saaz', 'yazim'], ['saazer', 'saaz', 'yazim'],
  ['zeus', 'columbus', 'urun'], ['ctz', 'columbus', 'yazim'], ['tomahawk', 'columbus', 'urun'],
  ['columbus (tomahawk)', 'columbus', 'yazim'],   ['columbus/tomahawk/zeus, ctz', 'columbus', 'yazim'], ['colombus', 'columbus', 'yazim'],
  ['equinox', 'ekuanot', 'urun'],
  ['german spalt select', 'spalt_sel', 'yazim'],   ['spalter', 'spalt', 'yazim'],
  ['vic secret', 'vic_secret', 'yazim'],
  ['lemon drop', 'lemondrop', 'yazim'],
  ['german perle', 'perle', 'yazim'],
  ['ella (stella)', 'ella', 'urun'],   ['hallertauer tradition', 'tradition', 'yazim'],   ['saphir (german organic)', 'saphir', 'yazim'],
  ['polish lublin', 'lublin', 'yazim'], ['lubelski', 'lublin', 'yazim'],
  ['hallertauer magnum', 'magnum', 'yazim'], ['magnum us', 'magnum', 'yazim'], ['german magnum', 'magnum', 'yazim'], ['us magnum', 'magnum', 'yazim'],
  ['denali', 'sultana', 'urun'],
  ['bavaria mandarina', 'mandarina', 'yazim'],   ['cascade us', 'cascade', 'yazim'], ['cascade (u.s.)', 'cascade', 'yazim'],   ['chinook us', 'chinook', 'yazim'], ['australian galaxy', 'galaxy', 'yazim'],
  ['yellow sub', 'yellow_sub', 'yazim'],
  ['citra lupuln2', 'lupulin_c', 'urun'],
    ['german northern brewer', 'nbrewer', 'yazim'],
  ['tettnang', 'tettn', 'yazim'], ['german tettnanger', 'tettn', 'yazim'],
  // L0'da yalnız ID ile eşleşenler → açık alias (bkz. MALT notu)
  ['columbus', 'columbus', 'jenerik'], ['saaz', 'saaz', 'jenerik'], ['spalt', 'spalt', 'jenerik'], ['tradition', 'tradition', 'yazim'],
  ['sultana', 'sultana', 'yazim'], ['lublin', 'lublin', 'yazim'], ['styrian', 'styrian', 'yazim'],
    ];

// MAYA: ham dizge "ad (lab, tip, %att)" → anahtar "ad (lab)". kod = token eşleşmesi.
const MAYA = [
  // Fermentis
  ['safale us-05 (fermentis)', 'us05', 'urun'], ['safale - american ale yeast us-05 (fermentis / safale)', 'us05', 'urun'],
  ['safale us-05', 'us05', 'urun'], ['fermentis safale us-05', 'us05', 'urun'],
  ['us-05', 'us05', 'kod'], ['us05', 'us05', 'kod'],
  ['safale s-04 (fermentis)', 's04', 'urun'], ['safale - english ale yeast s-04 (fermentis / safale)', 's04', 'urun'],
  ['safale s-04', 's04', 'urun'], ['fermentis safale s-04', 's04', 'urun'], ['s-04', 's04', 'kod'], ['s04', 's04', 'kod'],
  ['safbrew s-33 (fermentis)', 's33', 'urun'], ['safbrew - general/belgian yeast s-33 (fermentis / safale)', 's33', 'urun'], ['s-33', 's33', 'kod'],
  ['safbrew t-58 (fermentis)', 't58', 'urun'], ['safbrew - specialty ale yeast t-58 (fermentis / safale)', 't58', 'urun'], ['t-58', 't58', 'kod'],
  ['safbrew wb-06 (fermentis)', 'wb06', 'urun', 'ürün adı birebir; korpus att 75 brewtoad/brewersfriend veritabanı değeri; katalog 84-89 ayrı kaynaktan — kimlik değil DEĞER farkı'], ['safbrew - wheat beer yeast wb-06 (fermentis / safale)', 'wb06', 'urun'],
  ['fermentis wb-06 dry wheat beer yeast', 'wb06', 'urun', 'ürün adı birebir; korpus att 75 site veritabanı değeri — kimlik değil DEĞER farkı'], ['wb-06', 'wb06', 'kod'],
  ['saflager s-23 (fermentis)', 's23', 'urun'], ['saflager - german lager yeast s-23 (fermentis / safale)', 's23', 'urun'], ['s-23', 's23', 'kod'],
  ['saflager w-34/70 (fermentis)', 'w3470', 'urun', 'ürün adı birebir; korpus att 70 brewtoad/brewersfriend veritabanı değeri; katalog 80-84 ayrı kaynaktan — kimlik değil DEĞER farkı'], ['saflager - german lager yeast w-34/70 (fermentis / safale)', 'w3470', 'urun'],
  ['saflager w-34/70', 'w3470', 'urun'], ['fermentis saflager w-34/70', 'w3470', 'urun'], ['w-34/70', 'w3470', 'kod'], ['34/70', 'w3470', 'kod'],
  ['s-189', 's189', 'kod'],
  ['safale - german ale yeast k-97 (fermentis / safale)', 'k97', 'urun'], ['k-97', 'k97', 'kod'],
  // SafBrew Abbaye → BE-256 olarak yeniden adlandırıldı (aynı ürün)
  ['abbey ale (fermentis)', 'be256', 'urun'], ['safbrew - abbaye yeast (fermentis / safale)', 'be256', 'urun'], ['be-256', 'be256', 'kod'],
  ['be-134', 'be134', 'kod'],
  // Lallemand / Danstar
  ['nottingham ale yeast (danstar)', 'nottm', 'urun'], ['nottingham ale (danstar)', 'nottm', 'urun'], ['nottingham ale', 'nottm', 'urun'],
  ['nottingham ale yeast (white labs)', 'nottm', 'urun', 'brewtoad lab etiketi yanlış (Nottingham bir Lallemand/Danstar ürünü); ürün adı birebir, att 76 ≈ katalog'],
  ['nottingham ale yeast (ale)', 'nottm', 'urun'], ['nottingham ale (ale)', 'nottm', 'urun'], ['lallemand nottingham', 'nottm', 'urun'],
  ['danstar nottingham ale', 'nottm', 'urun'], ['nottingham', 'nottm', 'urun'],
  ['windsor ale yeast (danstar)', 'la_windsor', 'urun'], ['danstar windsor ale', 'la_windsor', 'urun'], ['windsor yeast', 'la_windsor', 'urun'],
  ['belle saison (danstar)', 'la_belle', 'urun'], ['belle saison yeast (danstar)', 'la_belle', 'urun'],
  ['american west coast yeast bry-97 (danstar)', 'la_bry97', 'urun'], ['bry-97 american west coast', 'la_bry97', 'urun'],
  ['bry-97 american west coast (danstar)', 'la_bry97', 'urun'], ['bry-97', 'la_bry97', 'kod'],
  // Wyeast (ürün adı + kod)
  ['american ale (wyeast)', 'wy1056', 'urun'], ['wyeast 1056', 'wy1056', 'urun'], ['1056', 'wy1056', 'kod'],
  ['american ale ii (wyeast)', 'wy1272', 'urun'], ['1272', 'wy1272', 'kod'],
  ['london ale iii (wyeast)', 'wy1318', 'urun'], ['1318', 'wy1318', 'kod'],
  ['london ale (wyeast)', 'wy1028', 'urun'], ['london ale 1028 (wyeast)', 'wy1028', 'urun'], ['1028', 'wy1028', 'kod'],
  ['irish ale (wyeast)', 'wy1084', 'urun'], ['1084', 'wy1084', 'kod'],
  ['scottish ale (wyeast)', 'wy1728', 'urun'], ['1728', 'wy1728', 'kod'],
  ['london esb ale (wyeast)', 'wy1968', 'urun'], ['1968', 'wy1968', 'kod'],
  ['weihenstephan weizen (wyeast)', 'wy3068', 'urun'], ['3068', 'wy3068', 'kod'],
  ['bavarian wheat (wyeast)', 'wy3638', 'urun'], ['3638', 'wy3638', 'kod'],
  ['belgian wit ale (wyeast)', 'wy3944', 'urun'], ['3944', 'wy3944', 'kod'],
  ['3522', 'wy3522', 'kod'],
  ['trappist high gravity (wyeast)', 'wy3787', 'urun'], ['trappist high gravity', 'wy3787', 'urun'], ['3787', 'wy3787', 'kod'],
  ['french saison (wyeast)', 'wy3711', 'urun'], ['3711', 'wy3711', 'kod'],
  ['belgian saison yeast (wyeast)', 'wy3724', 'urun'], ['belgian saison (wyeast)', 'wy3724', 'urun'], ['3724', 'wy3724', 'kod'],
  ['belgian strong ale (wyeast)', 'wy1388', 'urun'], ['belgian strong ale 1388 (wyeast)', 'wy1388', 'urun'], ['1388', 'wy1388', 'kod'],
  ['bavarian lager (wyeast)', 'wy2206', 'urun'], ['2206', 'wy2206', 'kod'],
  ['munich lager (wyeast)', 'wy2308', 'urun'], ['munich lager 2308 (wyeast)', 'wy2308', 'urun'], ['2308', 'wy2308', 'kod'],
  ['bohemian lager (wyeast)', 'wy2124', 'urun'], ['bohemian lager 2124 (wyeast)', 'wy2124', 'urun'], ['2124', 'wy2124', 'kod'],
  ['urquell lager (wyeast)', 'wy2001', 'urun'], ['2001', 'wy2001', 'kod'],
  ['california lager (wyeast)', 'wy2112', 'urun'], ['california lager 2112 (wyeast)', 'wy2112', 'urun'], ['2112', 'wy2112', 'kod'],
  // White Labs
  ['california ale yeast (white labs)', 'wlp001', 'urun'], ['california ale yeast wlp001 (white labs)', 'wlp001', 'urun'],
  ['california ale (white labs)', 'wlp001', 'urun'], ['wlp001', 'wlp001', 'kod'],
  ['english ale yeast (white labs)', 'wlp002', 'urun'], ['english ale yeast wlp002 (white labs)', 'wlp002', 'urun'], ['wlp002', 'wlp002', 'kod'],
  ['irish ale yeast (white labs)', 'wlp004', 'urun'], ['irish ale yeast wlp004 (white labs)', 'wlp004', 'urun'], ['wlp004', 'wlp004', 'kod'],
  ['dry english ale yeast (white labs)', 'wlp007', 'urun'], ['dry english ale yeast wlp007 (white labs)', 'wlp007', 'urun'], ['wlp007', 'wlp007', 'kod'],
  ['german ale/kölsch yeast (white labs)', 'wlp029', 'urun'], ['german ale/ kölsch yeast wlp029 (white labs)', 'wlp029', 'urun'],
  ['german ale/kölsch (white labs)', 'wlp029', 'urun'], ['wlp029', 'wlp029', 'kod'],
  ['hefeweizen ale yeast (white labs)', 'wlp300', 'urun'], ['hefeweizen ale yeast wlp300 (white labs)', 'wlp300', 'urun'], ['wlp300', 'wlp300', 'kod'],
  ['trappist ale yeast (white labs)', 'wlp500', 'urun'], ['trappist ale yeast wlp500 (white labs)', 'wlp500', 'urun'], ['wlp500', 'wlp500', 'kod'],
  ['belgian ale yeast (white labs)', 'wlp550', 'urun'], ['belgian ale yeast wlp550 (white labs)', 'wlp550', 'urun'], ['wlp550', 'wlp550', 'kod'],
  ['belgian saison i yeast (white labs)', 'wlp565', 'urun'], ['belgian saison i yeast wlp565 (white labs)', 'wlp565', 'urun'], ['wlp565', 'wlp565', 'kod'],
  ['belgian golden ale yeast (white labs)', 'wlp570', 'urun'], ['belgian golden ale yeast wlp570 (white labs)', 'wlp570', 'urun'], ['wlp570', 'wlp570', 'kod'],
  ['wlp585', 'wlp585', 'kod'],
  ['american farmhouse blend (wlp670)', 'wlp670', 'urun'], ['american farmhouse blend (wlp670) (white labs)', 'wlp670', 'urun'], ['wlp670', 'wlp670', 'kod'],
  ['pilsner lager yeast (white labs)', 'wlp800', 'urun'], ['pilsner lager yeast wlp800 (white labs)', 'wlp800', 'urun'], ['wlp800', 'wlp800', 'kod'],
  ['german lager yeast (white labs)', 'wlp830', 'urun'], ['german lager yeast wlp830 (white labs)', 'wlp830', 'urun'], ['wlp830', 'wlp830', 'kod'],
  ['southern german lager yeast (white labs)', 'wlp838', 'urun'], ['wlp838', 'wlp838', 'kod'],
  // Mangrove Jack's
  ['u.s. west coast (mangrove jack\'s)', 'mj_m44', 'urun'], ['us west coast yeast m44 (mangrove jack)', 'mj_m44', 'urun'],
  ['us west coast yeast (mangrove jack)', 'mj_m44', 'urun'], ['m44', 'mj_m44', 'kod'],
  ['belgian ale (mangrove jack\'s)', 'mj_m41', 'urun'], ['m41', 'mj_m41', 'kod'],
  ['bavarian wheat (mangrove jack\'s)', 'mj_m20', 'urun'], ['bavarian wheat yeast m20 (mangrove jack)', 'mj_m20', 'urun'], ['m20', 'mj_m20', 'kod'],
  ['bohemian lager (mangrove jack\'s)', 'mj_m84', 'urun'], ['m84', 'mj_m84', 'kod'],
  ['new world strong ale m42 (mangrove jack)', 'mj_m42', 'urun'], ['m42', 'mj_m42', 'kod'],
  ['liberty bell ale m36 (mangrove jack)', 'mj_m36', 'urun'], ['m36', 'mj_m36', 'kod'],
  ['californian lager m54 (mangrove jack)', 'mj_m54', 'urun'], ['m54', 'mj_m54', 'kod'],
  ['m15', 'mj_m15', 'kod'], ['m21', 'mj_m21', 'kod'], ['m29', 'mj_m29', 'kod'], ['m31', 'mj_m31', 'kod'],
  ['m47', 'mj_m47', 'kod'], ['m66', 'mj_m66', 'kod'], ['m76', 'mj_m76', 'kod'],
];

// BİLİNÇLİ RED — V2/V3'te eşlemesi olan ama KİMLİK olmayan (ikame/yaklaşık/belirsiz) ham adlar.
// Bunlar build-time iskelet hattında ikame olarak yaşamaya devam eder; katalog alias'ına GİRMEZ.
const REDDET = {
  hop: {
    'liberty': 'ayrı çeşit (Hallertau torunu) — V2 hrtau İKAMESİ',
    'mount hood': 'ayrı çeşit — V2 hrtau İKAMESİ', 'mt hood': 'ayrı çeşit', 'mt. hood': 'ayrı çeşit',
    'hersbrucker': 'ayrı çeşit (Hallertauer Hersbrucker) — V2 hrtau İKAMESİ',
    'hallertauer hersbrucker': 'ayrı çeşit — V3 hrtau İKAMESİ', 'german hallertauer hersbrucker': 'ayrı çeşit',
    'vanguard': 'ayrı çeşit — V2 hrtau İKAMESİ', 'strisselspalt': 'ayrı çeşit (Alsas) — V2 hrtau İKAMESİ',
    'new zealand hallertau': 'NZ Hallertau Aroma — ayrı çeşit', 'new zealand cascade': 'aynı kültivar, farklı terroir (alfa 8,7 vs 5,5)',
    'argentine cascade': 'farklı terroir (alfa 3,2)', 'tnt': 'katalog tnt = BiraBurada TnT karışımı; korpus «tnt» kaynağı belirsiz (L0 ID-eşlemesi)', 'mosaic lupuln2': 'katalogda Mosaic lupulin tozu yok',
  },
  malt: {
    'caramunich': 'I/II/III belirsiz — V2 cara_munich2 VARSAYIMI', 'crystal malt': '°L belirsiz', 'medium crystal': '°L belirsiz',
    'crystal 15l': 'katalogda 15L yok — V3 en-yakın-L c10 İKAMESİ', 'caramel/crystal 30l': 'katalogda 30L yok',
    'caramel/crystal 90l': 'katalogda 90L yok', 'crystal 135l': 'katalogda 135L yok', 'extra dark crystal 120l': 'Simpsons Extra Dark mı c120 mi belirsiz',
    'british crystal 135-165l': 'aralık belirsiz', 'caravienne': 'katalogda CaraVienne yok — V3 c20 İKAMESİ',
    'caraamber': 'katalogda yok — V3 c20 İKAMESİ', 'carastan': 'katalogda yok — V2 c40 İKAMESİ', 'carabrown': 'katalogda yok',
    'caramel pils': 'renk uyuşmuyor (8 vs 2)', 'caracrystal wheat malt': 'katalogda yok', 'caramel wheat': 'marka belirsiz',
    'carafa i': 'kabuklu Carafa ≠ katalogdaki Special (kabuksuz)', 'carafa ii': 'kabuklu ≠ Special', 'carafa iii': 'kabuklu ≠ Special',
    'special b malt': 'bkz. special b (L0)', 'chocolate rye': 'katalogda yok — V2 choc İKAMESİ',
    'golden naked oats': 'crystal yulaf ~10°L ≠ flaked oats — V3 oat İKAMESİ', 'munich malt 10l': 'Briess 10L ≠ Munich Type 1 (6) — renk kapısı',
    'munich 20l': 'renk ≠ dark_munich', 'munich malt - 20l': 'renk ≠ dark_munich', 'munich dark': 'renk 15,5 ≠ 9',
    'rahr 2-row pale': 'farklı malthane (Rahr ≠ Briess)', 'great western premium 2-row malt': 'farklı malthane',
    'canadian 2-row malt': 'farklı malthane', 'pale malt, 2 row, uk': 'V3 maris VARSAYIMI — İngiliz 2-row ≠ Maris Otter',
    'invert sugar': 'No.1/2/3 belirsiz — V2 invert2 VARSAYIMI', 'candi sugar, clear': 'kaya şeker ≠ şurup',
    'belgian candi syrup - d2': 'D2 (160) ≠ D-180', 'belgian dark candi syrup': 'derece belirsiz',
    'black patent malt': 'korpus rengi tutarsız (127°L)', 'american black patent': 'korpus rengi tutarsız (127°L)',
    'dark chocolate': 'marka belirsiz', 'black barley (stout)': 'black barley ≠ roasted barley',
    'amber malt (thomas faucett)': 'renk 42 ≠ 30', 'british amber': 'renk 60 ≠ 30', 'belgian biscuit malt': 'renk 18 ≠ 25',
    'brown sugar, light': 'renk 8 ≠ 20', 'mild': 'fawcett_mild/muntons_mild belirsiz', 'mild malt': 'iki aday',
    'lager': 'belirsiz', 'belgian carapils': 'renk 13 ≠ 2', 'debittered black malt': 'Dingemans ≠ jenerik dehusked',
    'danstar munich': 'eski Munich ≠ Munich Classic',
    'rice': 'katalog ID «rice» = Pirinç KABUĞU; korpusta «rice» = pirinç adjunct (L0 ID-eşlemesi bunu YANLIŞ bağlıyordu)',
  },
  maya: {
    'nottingham ale yeast (white labs)→s04': 'V2 YEAST_ID_RE nottingham→s04 İKAMESİ; kimlik nottm',
    'bry-97→us05': 'V2 İKAMESİ; kimlik la_bry97', 'windsor→s04': 'V2 İKAMESİ; kimlik la_windsor',
    '1968→s04': 'V2 İKAMESİ; kimlik wy1968', 'wlp001→us05': 'V2 İKAMESİ; kimlik wlp001',
  }
};

module.exports = { MALT, HOP, MAYA, REDDET };
