name = "brewmaster-models"
main = "src/index.js"
compatibility_date = "2025-05-01"
workers_dev = true

[[r2_buckets]]
binding = "MODELS"
bucket_name = "brewmaster-models"

[[kv_namespaces]]
binding = "BM_KV"
id = "b0427e55c6c642148b30f12c88c7e335"

[triggers]
crons = ["*/5 * * * *"]
